DATASET:
  root_dataset: "./dataset/Stanford2D3D"
  list_train: "./data/2D3DS_training.odgt"
  list_val: "./data/2D3DS_validation.odgt"
  num_class: 10
  imgMaxSize: 1024
  padding_constant: 8
  segm_downsampling_rate: 8
  random_flip: True

MODEL:
  arch_encoder: "resnet50dilated"
  arch_decoder: "ppm_deepsup"
  fc_dim: 2048

TRAIN:
  batch_size_per_gpu: 2
  num_epoch: 10
  start_epoch: -1
  epoch_iters: 1000
  optim: "SGD"
  lr_encoder: 0.02
  lr_decoder: 0.02
  lr_pow: 0.9
  beta1: 0.9
  weight_decay: 1e-4
  deep_sup_scale: 0.4
  fix_bn: False
  workers: 16
  disp_iter: 20
  seed: 304

VAL:
  visualize: False
  checkpoint: "epoch_10.pth"

DIR: "ckpt/pspnet-r"
